#! /bin/bash

# Script used for generating a new dropdown-menu
# The first line: The first sentence is the grouping.
# The second sentence is the subheader.
# Based on this, we can generate a cool navibar.

touch pages/marker
rm -r pages/*

# Process every page with m4
count=0
for j in preprocessed_pages/*; do
	mkdir -p pages/${j#preprocessed_pages/}
	for i in $(ls $j/* | sort -nr); do
		m4 "$i" > pages/"${i#preprocessed_pages/}"
		echo "<div id=\"navivalue\" hidden>$count</div>" >> pages/"${i#preprocessed_pages/}"
		: $((++count))
	done
done

cd pages/
out=../autogen/navigation
echo '<select name="page" onchange="httpGetAsyncPage(this.value,this.selectedIndex,getPage);">' > "$out"
lasthead=

for j in $(ls | sort -n); do
	cd $j
	for i in $(ls | sort -rn); do
		if [ -d $i ]; then
			break
		fi
		line=$(cat $i | head -n 1)
		head=$(echo "$line" | cut -d '.' -f 1)
		if [ "$head" != "$lasthead" ]; then
			if [ "$lasthead" != '' ]; then
				cd ..
				echo '</optgroup>' >> "$out"
				cd $j
			fi
			cd ..
			echo "<optgroup label=\"$head\">" >> "$out"
			cd $j
		fi
		lasthead="$head"
		sub=$(echo "$line" | cut -d '.' -f 2)
		cd ..
		echo "<option value=\"$i;$j\">${sub% }</option>" >> "$out"
		cd $j
	done
	cd ..
done

echo '</optgroup>' >> "$out"
echo '</select>' >> "$out"
sed -i "s/\n//g" "$out"
